from snakemake.remote import AUTO

rule calling_script:
    input:
        AUTO.remote("https://raw.githubusercontent.com/scikit-learn/scikit-learn/1.0/sklearn/datasets/data/iris.csv")
    output:
        "results/out.csv",
    container: "docker://julia"
    script:
        "bin/smk_script.jl"
