#+TITLE: Emacs email config
#+DATE: 2019-01-20T22:49:01-06:00
#+PUBLISHDATE: 2019-01-20T22:49:01-06:00
#+DRAFT: true
#+TAGS: emacs, email, notmuch, doom, ubuntu
#+DESCRIPTION: Setting up email in Emacs

* Introduction
Like most people these days I have quite a few email addresses, personal, old
personal email, and school. In the past I've tried using Emacs to manage all of
these in one place. However, when I added a work email account into the mix that
didn't have ~IMAP~ enabled it was finally enough to make me go back to using the
web clients.

Recently I started to get the itch to bring the config into my [[https://github.com/Emiller88/dotfiles][dotfiles]],
since the biggest pain was setting it all up on a new computer and making it
feel fragile.

**** Guides:
- [[https://bostonenginerd.com/posts/notmuch-of-a-mail-setup-part-1-mbsync-msmtp-and-systemd/]]
- [[http://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html]]
- [[https://youtu.be/obY1um6ehDM]]

**** Notmuch config of my dotfiles:
- [[https://github.com/Emiller88/dotfiles/tree/master/shell/notmuch]]

* Fetching the Mail
In the past I've tried [[https://github.com/OfflineIMAP/offlineimap][offlineimap]] but it's slow when you have to pull down
years and years of email. So I first started with [[https://wiki.archlinux.org/index.php/Isync][mbsync]](I've used the arch wiki
because it explains more than the actual documentation in my opinion).

To get that set up:
#+BEGIN_SRC sh
sudo apt install isync
#+END_SRC

and then add a ~~/.mbsyncrc~ file and configure it according to one of the above
guides or the [[https://wiki.archlinux.org/index.php/Isync][arch wiki]]. I will try to avoid going over things that I just copied and
pasted and they worked, in order to keep this short.

An issue that I ran into later down the road was that [[https://wiki.archlinux.org/index.php/Isync][mbsync]] doesn't sync just
any flag/label/tag back to gmail. Enter [[https://github.com/gauteh/gmailieer][gmailieer]]. Which was more of a pain to
setup.

To install from [[https://launchpad.net/ubuntu/+source/gmailieer][here]]
#+BEGIN_SRC sh
sudo apt-get install gmailieer
#+END_SRC

The chicken and the egg problem with ~gmailieer~ is that it needs ~notmuch~ set
up in the ~.mail~ dir. So when I was setting ~gmailieer~ up, ~notmuch~ was
already up and running for me. We'll come back to it.

With ~gmailieer~ the important part, is if I check my email on my phone, another
computer, or emacs, it will update as read, archived, deleted, and most
importantly the tags will be the same on it. For an added bonus it works for my
work account that uses Gsuite since it uses their api and not IMAP.

Next we need to setup the mail to be ran in the background every so often. This
[[https://bostonenginerd.com/posts/notmuch-of-a-mail-setup-part-1-mbsync-msmtp-and-systemd/%0A][guide]] has a great setup for it.
#+BEGIN_SRC sh
mklink checkmail.service $XDG_CONFIG_HOME/systemd/user/checkmail.service
mklink checkmail.timer $XDG_CONFIG_HOME/systemd/user/checkmail.timer
#+END_SRC

And start and enable the timer
#+BEGIN_SRC sh
systemctl --user start checkmail.timer
systemctl --user enable checkmail.timer
#+END_SRC

The ~checkmail.service~ calls ~checkmail.sh~
#+BEGIN_SRC sh
#!/usr/bin/env bash

STATE=$(nmcli networking connectivity)

if [ $STATE = 'full' ]; then
  echo "Syncing email1"
  cd /home/emiller/.mail/email1/
  gmi sync
  echo "Syncing email2"
  cd /home/emiller/.mail/email2/
  gmi sync
  echo "Syncing work"
  cd /home/emiller/.mail/work/
  gmi sync
  echo "Checking school"
	mbsync -V school
	exit 0
fi
echo "No internet connection."
exit 0
#+END_SRC

The ~gmi sync~ command does a ~push~ followed by a ~pull~ so the tags from the
local overwrite anything that's on the remote. So later we'll write rules to tag
the new mail coming in.

* Tagging the Mail
So the next step is to tag the mail. For that I use ~notmuch~. I tried ~mu~ in
the past but it works by moving the emails into various dirs instead of just
tagging them and I found it messed with how the remote emails were treated too
often.

#+BEGIN_SRC sh
sudo apt-get install notmuch
#+END_SRC
