#+title: Coming Home

Why I'm quitting [[https://k8s-at-home.com/][K8s at Home]] and running everything on [[https://nixos.org/][NixOS]].

So, I wanted to... Let's see, how do I start this? Ever since I found a series
of blog posts after ETH Denver in 2019 on creating a Kubernetes cluster to run a
media server at home using Raspberry Pis and an external drive. I think it dates
back even further in college I really had a dream of running a media server for
my friends because we are constantly wanting to watch old random movies, TV
shows that we're just struggling with all the streaming outlets at the time. So,
the concept that I has been there for a while. So, I originally tried to do it
with some Raspberry Pi's that I had laying around. Didn't really work out I got
k3s installed and stuff connected but I could never find a clean solution to
only use the VPN for qb.

So yeah, then I started to kind of play around with the various, you know, went
through that implementation, couldn't quite get the VPN connecting to the
torrent client was always just off. And so the dream died for a while. And then
I'd bring it back. And then it'd die again because I would never get it up
stuff. And then I found k8s@home. And I got pretty fare. And then it'd die
again, because I had a dream that this cluster would be a retirement home for
all of my old laptops and single board computers collecting dust.

Eventually I threw enough money at the hobby to get three intel NUCs setup and
got the proper hardware. And it's kind of running just on its own right
now[fn:1]. It seems to be working. The real issue, per se, is that I'm not
actually running updates like I should be despite the pull requests from
renovate. The images are staying up to date, but the code is rotting because
FluxCD seems to always be updating the syntax.So while I have learned all the
Kubernetes lingo that I wanted to learn, after you learn all of the deployment,
service, pod, ingress jargon, and peak behind the curtain the appeal kind of
wears off.

 Or like it is awesome. It works. It's so cool. It's great. So lovely tools. The
 real issue is that all the benefits that I had dreamed up and imagined with my
 naive self four or five years ago was that I'm not getting any of those actual
 benefits. I imagined a world where, oh, what am I? SD cards goes out on my pie
 and suddenly like, oh, all of my pods switch over and the services never go
 down. Cool. Yeah, that doesn't actually happen with a three note cluster, even
 in high availability. The pod just kind of sit there on a sign. So pause. This
 is definitely user error. I'm sure I could get that going. The point being of
 like it doesn't just come out of the box easy like I thought it did. Despite
 having high availability storage and all kinds of other things on that. This is
 going to be controversial. Yes, that's fine. The main thing being of I thought
 it just got to came out of the box and it just worked. Obviously, this is why
 we have entire day jobs for people who do this on the regular. And if I did
 this for a day job, that'd be cool. But this was literally just a side hobby to
 learn about Kubernetes. So I did it. I had a lot of fun with it. I learned a
 lot. It's come in beneficial to player out Kubernetes that much and be in to
 me, where I've it. So new header. Why am I where am I going from from here? I'm
 going back to next. That is my bread and butter. I love it. It just works. It
 gets updated by the huge packages repository. It doesn't work. I can hack on it
 and get it going. It's declarative. So I just write out what I want and then it
 figures it out. I don't have to constantly be updating it based on new versions
 and whatnot of things. It's just a config in that sense. Sorry, in my dot
 files, I just want to extend it. So what am I planning? I'm just going to run
 the NAS by itself for backups, syncing, storage as well on those. Then I'm just
 going to try to run one of the NUXs first, see what services I actually really
 want. I was just like, oh, that's kind of cool from the case at home people.
 And then I'm going to try running maybe a second knock, maybe an old laptop or
 something as well if I need to scale that at all. And that'll just be another
 config in my Gix.files. It's pretty simple. So the quarter mile turn right onto
 Preston Road. The question I guess is like, what happens if a node goes down?
 Well, because of Nix, I'm not really beholden to a specific computer. I can
 literally just spin up a new one and throw up just Nix install boom. I'm off to
 the races and I have a new node up. Take the next right on the Preston Road. So
 I don't really have to back it up. Besides the config and the actual data,
 which I'm right backing up the data. So maybe I should be doing a better job
 backing up the data and caring about that and less caring about the actual
 nodes and the confids and backing up databases and whatnot, our fancy
 databases. I should say. So yeah, turn your back on. Turn your back on. Turn
 your back on. Turn your back on. Then your destination will be on the right.
 Hopefully that the other cool feature that I wanted to mention that I really
 got from the days at home was the creation of new services and then creating
 new subdomains on my home services domain. That was really cool. That was what
 really brought me in as well was just a pot of provisioning of that. I'm pretty
 sure I can do that in Nix in a similar fashion or otherwise. So yeah, I think I
 was just a little scared of it with the whole Nix config. I realized that
 Kubernetes is even scarier than Nix. So I'm going back. Peace.


* Footnotes

[fn:1] Update the NUCs didn't give out but the HDD disks that I wasn't paying
attention to be I was constantly wrangling cattle died.
