#+title: Using Age with org-journal
#+DATE: 2023-12-15T11:00Z

* The problem

** Why not just use gpg?

Because [[https://dev.gnupg.org/T6481][gpg 2.4.1 borked]] Emacs's EasyPG. It just hangs on saving.

There are some ways around it, and I was using the ~fset~ hack until I read this
[[https://www.reddit.com/r/emacs/comments/18d6fmt/how_to_lock_yourself_out_of_a_gpg_encrypted_file/][post about the person who corrupted their encrypted files]]. I also had to run the
elisp on every new Emacs instance.

And then ~lib-gcrypt~ is marked as broken in NixOS if you use the ~gnupg22~
package(Version: 2.2.41), and a blowing past that stop sign sounded like a bad
idea.

So I started thinking outside the box.

** Why [[https://github.com/FiloSottile/age][age]]?

I started using it with [[https://github.com/ryantm/agenix][agenix]], just because [[https://github.com/hlissner/][Henrik]] started using it in his
dotfiles. The [[https://github.com/onedr0p/flux-cluster-template][k8s@home template]] also eventually [[https://github.com/onedr0p/flux-cluster-template/pull/153][switched from gpg to age]] so I
was already pretty comfortable with using age.

TL;DR [[https://nixfaq.org/2021/01/age-the-modern-alternative-to-gpg.html][Age: the modern alternative to GPG — nixFAQ]]:

- Age is presented as a modern alternative to GPG that solves many of its
  limitations while maintaining security.
- Age stands for "Actually Good Encryption" and has implementations in Go and
  Rust for improved security compared to GPG's C implementation.
- Age uses smaller keys that are easier to store physically and has a simpler
  interface with no configuration options.
- Files can be encrypted for multiple recipients simultaneously using Age.
- Age supports encrypting for SSH public keys in addition to its own keys.
- Age allows encrypting files for GitHub users by using their SSH keys from
  their profile.
- Age offers a better user experience than GPG while maintaining an equally high
  level of security.

** Why still org-journal?

I've thought about using [[https://www.orgroam.com/manual.html#org_002droam_002ddailies][org-roam-dailies]] instead of [[https://github.com/bastibe/org-journal][org-journal]]. Honestly after
going through this I'm not exactly sure why. [[https://github.com/anticomputer/age.el#org-roam-support-for-age-encrypted-org-files][Org Roam supports age]], and
[[https://github.com/bastibe/org-journal/issues/400][org-journal has quite a few PR fixes for various things that have been
ignored]](Not a judgement of the maintainer, just issues like [[https://github.com/bastibe/org-journal/issues/375][journal files are
decrypted whenever the calendar is invoked]] that make my life painful). I think
I was just looking for a quick fix to get back on with journaling.

* Setup

Now that you've all listened to me ramble on for a bit, here's the actual setup.
This is using [[https://github.com/doomemacs/doomemacs][Doom Emacs]].


~packages.el~
#+begin_src elisp
(package! age)
#+end_src

~config.el~
#+begin_src elisp
(use-package! age
  :init
  (setq! age-program "rage")
  :config
  (setq! age-default-identity "~/.ssh/id_ed25519"
         age-default-recipient "~/.ssh/id_ed25519.pub")
  (age-file-enable))
#+end_src

Went with [[https://github.com/str4d/rage][rage]], because Rust. Also there's [[https://github.com/anticomputer/age.el#workaround-pinentry-support-through-rage][pinentry support through rage]].

~config.el~
#+begin_src elisp
(after! org
  (setq org-journal-encrypt-journal nil
        org-journal-file-format "%Y%m%d.org.age")
#+end_src

Only thing I had to do then was turn off the built-in gpg support on
org-journal, and update the naming scheme to have age as the suffix and it just
worked.™
