name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.8.0
          run_install: false

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 24.17.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run format check
        run: pnpm format:check

      - name: Run lint
        run: pnpm lint

        # use astro check for issues
      - name: Run check
        run: pnpm astro check

        # ensure build works
      - name: Run build
        run: pnpm build
