name: Openring

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # openring
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v8 # This action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Run openring
        run: nix develop --impure --command .github/openring.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Run Openring
