name: Publish

on:
  push:
    branches:
      # TODO - master
      - org-publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Org Files
        uses: maker2413/OrgPublish@v1.0.0
        with:
          publish_script: publish.el
