name: Publish

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # openring
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4 # This action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Install devenv.sh
        run: nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest
        shell: sh
      # TODO
      # - name: Test devenv
      #   run: nix develop --command devenv ci
      - name: Setup Emacs
        run: nix develop --impure --command emacs --batch --load ./install.el
      # TODO Cache emacs

      - name: Publish Org Files
        run: nix develop --impure --command build-site

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT }}
          directory: ./dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ github.token }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: ${{ github.ref_name }}
          # Optional: Change the working directory
          # workingDirectory: my-site
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          # wranglerVersion: '3'
