flowchart TD
    p1[Group of Bams]
    p2[Bed file of de novo transcripts]
    p3[Bed file of TREs - bidirectional peaks]
    p4[Promoters.bed]
    p5[Candidate enhancer TSS]
    p6(bedtools intersect -v)
    p7(Filtered eRNA transcripts)


    p1 -->|homer gro-seq| p2
    p1 -->|PINTS| p3

    p3 --> p6
    p4 --> p6
    p6 --> p5
    p5 -->|Overlap| p7
    p2 -->|Overlap| p7
